apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "localstack.fullname" . }}
  labels:
    {{- include "localstack.labels" . | nindent 4 }}
data:
  # When the config map is mounted as a volume, these will be created as files.
  SERVICES: {{ .Values.app.services }}
  PORT_WEB_UI: "{{ .Values.app.port_web_ui }}"
  DOCKER_HOST: {{ .Values.app.docker_host }}
