apiVersion: v1
kind: Service
metadata:
  name: {{ include "localstack.fullname" . }}
  labels:
    {{- include "localstack.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.image.containerPort }}
      protocol: TCP
      name: http
    - port: {{ .Values.app.port_web_ui }}
      targetPort: {{ .Values.app.port_web_ui }}
      protocol: TCP
      name: webui
  selector:
    {{- include "localstack.selectorLabels" . | nindent 4 }}
